export const monColosseumAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "_character", type: "address", internalType: "address" },
      { name: "_vault", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "MATCHING_TIMEOUT",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "MAX_COLOSSEUM_SIZE",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "battlesByRound",
    inputs: [
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      { name: "winnerNftId", type: "uint256", internalType: "uint256" },
      { name: "loserNftId", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "colosseumExists",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "colosseums",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "buyIn", type: "uint256", internalType: "uint256" },
      { name: "createdAt", type: "uint256", internalType: "uint256" },
      { name: "isMatchingNow", type: "bool", internalType: "bool" },
      {
        name: "matchingStartTime",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "createNewColosseum",
    inputs: [{ name: "buyIn", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "enterColosseum",
    inputs: [
      { name: "nftId", type: "uint256", internalType: "uint256" },
      { name: "colosseumId", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "exitColosseum",
    inputs: [
      { name: "nftId", type: "uint256", internalType: "uint256" },
      { name: "colosseumId", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "gameMaster",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getActiveNFTs",
    inputs: [{ name: "colosseumId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getIsMatchingNow",
    inputs: [{ name: "colosseumId", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "monCharacter",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract IMONCharacter",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "monCharacterVault",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract IMONCharacterVault",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nextColosseumId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nextRoundId",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nftToColosseum",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nftToIndex",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "rounds",
    inputs: [
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      { name: "colosseumId", type: "uint256", internalType: "uint256" },
      { name: "seed", type: "bytes32", internalType: "bytes32" },
      { name: "createdAt", type: "uint256", internalType: "uint256" },
      { name: "playersCount", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setGameMaster",
    inputs: [{ name: "_gameMaster", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "submitBattleResults",
    inputs: [
      { name: "colosseumId", type: "uint256", internalType: "uint256" },
      { name: "roundId", type: "uint256", internalType: "uint256" },
      { name: "winners", type: "uint256[]", internalType: "uint256[]" },
      { name: "losers", type: "uint256[]", internalType: "uint256[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "triggerRound",
    inputs: [{ name: "colosseumId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "ColosseumCreated",
    inputs: [
      {
        name: "colosseumId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "buyIn",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EnteredColosseum",
    inputs: [
      {
        name: "nftId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "colosseumId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ExitedColosseum",
    inputs: [
      {
        name: "nftId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "colosseumId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RoundStarted",
    inputs: [
      {
        name: "roundId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "colosseumId",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "roundSeed",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Shuffled",
    inputs: [
      {
        name: "roundId",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "shuffled",
        type: "uint256[]",
        indexed: false,
        internalType: "uint256[]",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
];
